# fly.toml app configuration file generated for wild-tree-309 on 2023-10-24T05:48:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-tree-309"
primary_region = "ams"

[build]

[env]
  PORT ="3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
